jobs:
  - job: Plan_${{ parameters.environment }}_${{ parameters.component }}
    pool:
      vmImage: ${{ parameters.agentPool }}
    steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: ${{ parameters.terraformVersion }}
      - task: TerraformCLI@2
        displayName: Init - ${{ parameters.environment }} - ${{ parameters.component }}
        inputs:
          command: 'init'
          commandOptions: '-lock=false' # don't lock on PRs / validate phase
          backendType: 'azurerm'
          backendServiceArm: '${{ parameters.service_connection }}'
          backendAzureRmResourceGroupName: '${{ parameters.storage_account_rg }}'
          backendAzureRmStorageAccountName: '${{ parameters.storage_account_name }}'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: '${{ parameters.component }}.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
      - task: TerraformCLI@2
        displayName: Plan - ${{ parameters.environment }} - ${{ parameters.component }}
        inputs:
          command: 'plan'
          commandOptions: '-var-file=${{ parameters.tfvarsFile }} -var builtFrom=${{ parameters.builtFrom }} -out=${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceName: '${{ parameters.service_connection }}'
      - task: Bash@3
        displayName: "Remove local tfstate"
        inputs:
          targetType: 'inline'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          script: |
            rm -f terraform.tfstate* && rm -rf .terraform/
      - publish: $(System.DefaultWorkingDirectory)/${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan
        artifact: ${{ parameters.environment }}${{ parameters.component }}${{ parameters.build }}plan
