# Docs:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

variables:
  - name: terraformVersion
    value: 1.4.6
  - name: timeoutInMinutes
    value: "60"
  - name: agentPool
    value: ubuntu-22.04
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: cft-jenkins
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries
    

parameters:
  - name: environment_components
    type: object
    default:
    - deployment: 'ptlsbox_response'
      environment: 'ptlsbox'
      component: 'response'
      service_connection: 'DTS-CFTSBOX-INTSVC'
      storage_account_rg: 'core-infra-intsvc-rg'
      storage_account_name: 'cftsboxintsvc'
      tfvars_file: 'ptlsbox.tfvars'
      backend_resource_group_name: ''
      dependsOn: 'Precheck'
    - deployment: 'ptl_response'
      environment: 'ptl'
      component: 'response'
      service_connection: 'DTS-CFTPTL-INTSVC'
      storage_account_rg: 'core-infra-intsvc-rg'
      storage_account_name: 'cftptlintsvc'
      tfvars_file: 'ptl.tfvars'
      backend_resource_group_name: ''
      dependsOn: 'ptlsbox_response'

stages:
  - stage: Precheck
    jobs:
      - job: Precheck
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: 'DCD-CFT-Sandbox'
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          pool:
            vmImage: ${{ variables.agentPool }}
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
          - template: steps/terraform.yaml@cnp-azuredevops-libraries
            parameters:
              overrideAction: ${{ parameters.overrideAction }}
              environment: ${{ deployment.environment }}
              component: ${{ deployment.component }}
              serviceConnection: ${{ deployment.service_connection }}
              terraformInitSubscription: ${{ variables.terraformInitSubscription }}
              backendResourceGroupName: ${{ deployment.backend_resource_group_name }}
              product: ${{ variables.product }}
              tfvars_file: ${{ deployment.tfvars_file }}
