# Docs:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
      - master

resources:
  repositories:
  - repository: cnp-azuredevops-libraries
    type: github
    ref: refs/heads/master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

variables:
  - name: terraformVersion
    value: 1.4.5
  - name: timeoutInMinutes
    value: "60"
  - name: agentPool
    value: ubuntu-22.04
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: response
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy
  - name: environment_components
    type: object
    default:
    - deployment: 'ptlsbox_response'
      environment: 'ptlsbox'
      component: 'response'
      service_connection: 'DTS-CFTSBOX-INTSVC'
      storage_account_rg: 'core-infra-intsvc-rg'
      storage_account_name: 'cftsboxintsvc'
      backend_resource_group_name: 'core-infra-intsvc-rg'
      terraformInitSubscription: '1497c3d7-ab6d-4bb7-8a10-b51d03189ee3'
      dependsOn: 'Precheck'
    - deployment: 'ptl_response'
      environment: 'ptl'
      component: 'response'
      service_connection: 'DTS-CFTPTL-INTSVC'
      storage_account_rg: 'core-infra-intsvc-rg'
      storage_account_name: 'cftptlintsvc'
      backend_resource_group_name: 'core-infra-intsvc-rg'
      terraformInitSubscription: '1baf5470-1c3e-40d3-a6f7-74bfbce4b348'
      dependsOn: 'ptlsbox_response'

stages:
  - stage: Precheck
    jobs:
      - job: Precheck
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: 'DCD-CFT-Sandbox'
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each deployment in parameters.environment_components }}:
    - stage: ${{ deployment.deployment }}
      dependsOn: ${{ deployment.dependsOn }}
      jobs:
        - job: TerraformPlanApply
          pool:
            vmImage: ${{ variables.agentPool }}
          timeoutInMinutes: ${{ variables.timeoutInMinutes }}
          steps:
          - template: steps/terraform.yaml@cnp-azuredevops-libraries
            parameters:
              overrideAction: ${{ parameters.overrideAction }}
              environment: ${{ deployment.environment }}
              component: ${{ deployment.component }}
              serviceConnection: ${{ deployment.service_connection }}
              terraformInitSubscription: ${{ deployment.terraformInitSubscription }}
              backendResourceGroupName: ${{ deployment.backend_resource_group_name }}
              backendStorageAccountName: ${{ deployment.storage_account_name }}
              backendContainerName: 'tfstate'
              backendKey: ${{ deployment.component }}.tfstate
              product: ${{ variables.product }}
